import { NavigationGroup } from "@/types";

export const NAVIGATION_GROUPS: NavigationGroup[] = [
  {
    id: "workspaces",
    title: "Role Workspaces",
    items: [
      {
        id: "candidate-portal",
        title: "Candidate Portal",
        href: "/candidate",
        iconName: "UserCheck",
        requiredCapability: "portal.candidate.access",
      },
      {
        id: "employee-portal",
        title: "Employee Portal",
        href: "/employee",
        iconName: "User",
        requiredCapability: "portal.employee.access",
      },
      {
        id: "manager-workspace",
        title: "Team Leadership",
        href: "/manager",
        iconName: "Users",
        requiredCapability: "portal.manager.access",
      },
      {
        id: "recruiter-workspace",
        title: "Talent Acquisition",
        href: "/recruiter",
        iconName: "UserSearch",
        requiredCapability: "portal.recruiter.access",
      },
      {
        id: "hr-workspace",
        title: "Workforce Operations",
        href: "/hr",
        iconName: "Briefcase",
        requiredCapability: "portal.hr.access",
      },
      {
        id: "leadership-console",
        title: "Executive Intelligence",
        href: "/leadership",
        iconName: "BarChart3",
        requiredCapability: "portal.leadership.access",
      },
      {
        id: "admin-access",
        title: "Access Management",
        href: "/admin/access",
        iconName: "ShieldAlert",
        requiredCapability: "admin.access",
      },
    ],
  },
  {
    id: "recruitment-intelligence",
    title: "Recruitment Intelligence",
    items: [
      {
        id: "rec-jobs",
        title: "Job Requisitions",
        href: "/recruitment/jobs",
        iconName: "Briefcase",
        allowedRoles: ["recruiter", "hr", "manager", "leadership", "administrator"],
      },
      {
        id: "rec-new-job",
        title: "New Job Opening",
        href: "/recruitment/jobs/new",
        iconName: "FilePlus",
        allowedRoles: ["recruiter", "hr", "administrator"],
      },
    ],
  },
  {
    id: "adaptive-onboarding",
    title: "Adaptive Onboarding",
    items: [
      {
        id: "onb-hr-hub",
        title: "HR Onboarding Hub",
        href: "/hr/onboarding",
        iconName: "Briefcase",
        allowedRoles: ["hr", "recruiter", "administrator"],
      },
      {
        id: "onb-new-case",
        title: "Initiate Onboarding",
        href: "/hr/onboarding/new",
        iconName: "FilePlus",
        allowedRoles: ["hr", "administrator"],
      },
      {
        id: "onb-mgr-hub",
        title: "Manager Onboarding",
        href: "/manager/onboarding",
        iconName: "Users",
        allowedRoles: ["manager", "leadership", "administrator"],
      },
      {
        id: "onb-employee-journey",
        title: "My Onboarding Journey",
        href: "/onboarding",
        iconName: "UserCheck",
        allowedRoles: ["employee", "candidate", "manager", "hr", "administrator"],
      },
    ],
  },
  {
    id: "workforce-foundation",
    title: "Workforce Foundation",
    items: [
      {
        id: "wf-departments",
        title: "Departments & Org Tree",
        href: "/workforce/departments",
        iconName: "Building2",
        allowedRoles: ["employee", "manager", "recruiter", "hr", "leadership", "administrator"],
      },
      {
        id: "wf-roles",
        title: "Job Role Catalog",
        href: "/workforce/roles",
        iconName: "BookOpen",
        allowedRoles: ["employee", "manager", "recruiter", "hr", "leadership", "administrator"],
      },
      {
        id: "wf-skills",
        title: "Skill Taxonomy & Graph",
        href: "/workforce/skills",
        iconName: "Share2",
        allowedRoles: ["candidate", "employee", "manager", "recruiter", "hr", "leadership", "administrator"],
      },
      {
        id: "wf-candidates",
        title: "Candidate Profiles & Twins",
        href: "/workforce/candidates",
        iconName: "UserSearch",
        allowedRoles: ["recruiter", "hr", "administrator"],
      },
      {
        id: "wf-employees",
        title: "Employee Directory & Twins",
        href: "/workforce/employees",
        iconName: "Users",
        allowedRoles: ["employee", "manager", "recruiter", "hr", "leadership", "administrator"],
      },
      {
        id: "wf-policies",
        title: "Policy Documents",
        href: "/workforce/policies",
        iconName: "FileText",
        allowedRoles: ["employee", "manager", "recruiter", "hr", "leadership", "administrator"],
      },
      {
        id: "wf-data-quality",
        title: "Data Quality Engine",
        href: "/workforce/data-quality",
        iconName: "AlertCircle",
        allowedRoles: ["hr", "administrator"],
      },
    ],
  },
  {
    id: "decision-intelligence",
    title: "Decision Intelligence",
    items: [
      {
        id: "hr-decision-dashboard",
        title: "HR Decision Dashboard",
        href: "/dashboard",
        iconName: "LayoutDashboard",
        allowedRoles: ["hr", "manager", "leadership", "administrator"],
      },
      {
        id: "workforce-intelligence",
        title: "Workforce Intelligence",
        href: "/workforce/intelligence",
        iconName: "BarChart3",
        allowedRoles: ["hr", "manager", "leadership", "administrator"],
      },
      {
        id: "policy-rag-portal",
        title: "Policy Reasoning & RAG",
        href: "/policies",
        iconName: "FileText",
        allowedRoles: ["employee", "candidate", "manager", "recruiter", "hr", "leadership", "administrator"],
      },
      {
        id: "recommendations-workflow",
        title: "Recommendations & Actions",
        href: "/recommendations",
        iconName: "AlertCircle",
        allowedRoles: ["manager", "hr", "leadership", "administrator"],
      },
    ],
  },
  {
    id: "account-governance",
    title: "Governance",
    items: [
      {
        id: "my-access",
        title: "My Access & Scope",
        href: "/my-access",
        iconName: "Shield",
      },
    ],
  },
  {
    id: "foundation",
    title: "Platform Foundation",
    items: [
      {
        id: "overview",
        title: "Platform Overview",
        href: "/",
        iconName: "LayoutDashboard",
        disabled: false,
      },
      {
        id: "demo-experience",
        title: "Demo Experience & Golden Path",
        href: "/demo",
        iconName: "Sparkles",
        disabled: false,
      },
      {
        id: "system-status",
        title: "System Status",
        href: "/status",
        iconName: "Activity",
        disabled: false,
      },
      {
        id: "design-system",
        title: "Design System",
        href: "/design-system",
        iconName: "Palette",
        disabled: false,
      },
    ],
  },
];
